# Page tree
nav:
  - Home: notes.md
  - Large Language Models (LLM):
    - Introduction: llm/llm.md
    - Resources: llm/resources.md
  - Machine Learning:
    - Introduction: ml/ml.md
    - Types of Learning: 
      - Overview: ml/types.md
      - Supervised Learning: ml/type/supervised-learning.md
      - Unsupervised Learning: ml/type/unsupervised-learning.md
      - Semi-Supervised Learning: ml/type/semi-supervised-learning.md
      - Reinforcement Learning: ml/type/reinforcement-learning.md
    - Resources: ml/resources.md
  - Math4ML:
    - Introduction: math4ml/math4ml.md
    - Linear Algebra:
      - Resources: math4ml/linearalgebra/resources.md
  - Natural Language Processing (NLP):
    - Introduction: nlp/nlp.md
    - Resources: nlp/resources.md
  - Graphs:
    - Introduction: graphs/graphs.md
    - Resources: graphs/resources.md
  - Python:
    - Introduction: python/python.md
    - Language:
      - Functions: python/language/functions.ipynb
      - Lists: python/language/lists.ipynb
      - Modules: python/language/modules.ipynb
      - Strings: python/language/strings.ipynb
      - Exceptions: python/language/exceptions.ipynb
      - Tuples: python/language/tuples.ipynb
      - Dictionaries: python/language/dictionaries.ipynb
      - Counter: python/language/counter.ipynb
      - Sets: python/language/sets.ipynb
      - Control Flow: python/language/controlflow.ipynb
      - Sorting: python/language/sorting.ipynb
      - List Comprehensions: python/language/listcomprehensions.ipynb
    - Visualization:
      - Matplotlib: python/visualization/matplotlib.ipynb

# Project information
site_name: Notes
site_url: https://amgadmadkour.github.io/notes/notes.md
site_author: Amgad Madkour

# Repository
repo_name: amgadmadkour/notes
repo_url: https://github.com/amgadmadkour/notes
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 - Amgad Madkour

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white 
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black 
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections

use_directory_urls : False

extra:
  homepage: https://amgadmadkour.github.io/

markdown_extensions:
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets:
        auto_append:
          - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - admonition
  - pymdownx.details

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mknotebooks:
      enable_default_jupyter_cell_styling: true
      enable_default_pandas_dataframe_styling: true
  - print-site
  - autorefs
